name: Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout

      - uses: actions/setup-node
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: Make init
        run: make init

      - name: Make init
        run: make init

      - name: Make lint
        run: make lint

      - name: Make build
        run: make build
